FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Intelligent Autonomous Bot Framework API Documentation

This is a framework to make you create a chatbot more easily.

## Getting Started [/questions]